version: '3.8'

# Configuration block for Airflow services
x-airflow-common: &airflow-common
  image: apache/airflow:2.8.0
  environment: &airflow-env
    AIRFLOW__CORE__EXECUTOR: SequentialExecutor # Simple executor for local testing
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__FERNET_KEY: '' # Not used with SQLite
    AIRFLOW__CORE__DAG_FOLDER: /opt/airflow/dags
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db # SQLite DB
  env_file:
    - .env # Load IQAir API key
  volumes:
    - ./airflow/logs:/opt/airflow/logs # Persist logs
    - ./airflow/dags:/opt/airflow/dags # DAG definitions
    - ./src:/opt/airflow/src # Python scripts
    - ./data:/opt/airflow/data # Raw/cleaned data files
    - airflow_db:/opt/airflow  # Airflow DB 
  user: "${AIRFLOW_UID:-50000}:0" # User config

services:
  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    command: webserver
    ports:
      - "8080:8080" # Airflow UI
    depends_on:
      - airflow-scheduler
    environment:
      - IQAIR_API_KEY=${IQAIR_API_KEY} # API key from .env

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: scheduler # Runs scheduled tasks

volumes:
  airflow_db: 
