version: '3.8'

x-airflow-common: &airflow-common
  image: apache/airflow:2.8.0
  environment: &airflow-env
    AIRFLOW__CORE__EXECUTOR: SequentialExecutor
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAG_FOLDER: /opt/airflow/dags
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
  env_file:
    - .env
  volumes:
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/src:/opt/airflow/src
    - ./airflow/data:/opt/airflow/data
    - airflow_db:/opt/airflow
  user: "${AIRFLOW_UID:-50000}:0"

services:
  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      - airflow-scheduler
    environment:
      - IQAIR_API_KEY=${IQAIR_API_KEY}

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: scheduler

volumes:
  airflow_db:  # 👈 this ensures sqlite DB is saved
