import json

cities = [
    {"city": "Canberra", "state": " ACT", "country": "Australia"},
    {"city": "Vienna", "state": "Vienna", "country": "Austria"},
    {"city": "Brussels", "state": "Brussels Capital", "country": "Belgium"},
    {"city": "Toronto", "state": "Ontario", "country": "Canada"},
    {"city": "Santiago", "state": "Santiago Metropolitan", "country": "Chile"},
    {"city": "Bogota", "state": "Bogota D.C.", "country": "Colombia"}, 
    {"city": "San Jose", "state": "San Jose", "country": "Costa Rica"},
    {"city": "Prague", "state": "Praha", "country": "Czech Republic"},
    {"city": "Copenhagen", "state": "Capital Region", "country": "Denmark"},
    {"city": "Tallinn", "state": "Harjumaa", "country": "Estonia"},
    {"city": "Helsinki", "state": "Uusimaa", "country": "Finland"},
    {"city": "Paris", "state": "Ile-de-France", "country": "France"},
    {"city": "Berlin", "state": "Berlin", "country": "Germany"},
    {"city": "Athens", "state": "Attica", "country": "Greece"},
    {"city": "Budapest", "state": "Central Hungary", "country": "Hungary"},
    {"city": "Reykjavik", "state": "Capital Region", "country": "Iceland"},
    {"city": "Dublin", "state": "Leinster", "country": "Ireland"},
    {"city": "Jerusalem", "state": "Jerusalem", "country": "Israel"},
    {"city": "Rome", "state": "Latium", "country": "Italy"},
    {"city": "Tokyo", "state": "Tokyo", "country": "Japan"},
    {"city": "Riga", "state": "Riga", "country": "Latvia"}, 
    {"city": "Vilnius", "state": "Vilnius", "country": "Lithuania"},
    {"city": "Luxembourg", "state": "District de Luxembourg", "country": "Luxembourg"},
    {"city": "Mexico City", "state": "Mexico City", "country": "Mexico"},
    {"city": "Amsterdam", "state": "North Holland", "country": "Netherlands"},
    {"city": "Auckland", "state": "Auckland", "country": "New Zealand"},
    {"city": "Oslo", "state": "Oslo", "country": "Norway"},
    {"city": "Warsaw", "state": "Mazovia", "country": "Poland"},
    {"city": "Lisbon", "state": "Lisbon", "country": "Portugal"},
    {"city": "Bratislava", "state": "Bratislava", "country": "Slovakia"}, 
    {"city": "Ljubljana", "state": "Osrednjeslovenska", "country": "Slovenia"},
    {"city": "Seoul", "state": "Seoul", "country": "South Korea"},
    {"city": "Madrid", "state": "Madrid", "country": "Spain"},
    {"city": "Stockholm", "state": "Stockholm", "country": "Sweden"},
    {"city": "Bern", "state": "Bern", "country": "Switzerland"},
    {"city": "Istanbul", "state": "Istanbul", "country": "Turkey"},
    {"city": "London", "state": "England", "country": "United Kingdom"},
    {"city": "Washington D.C.", "state": "District of Columbia", "country": "USA"}
]